var geejson4H = {
    "type": "FeatureCollection",
    "name": "4h",
    "crs": {
        "type": "name",
        "properties": {
            "name": "urn:ogc:def:crs:OGC:1.3:CRS84"
        }
    },
    "features": [{
            "type": "Feature",
            "properties": {
                "year": 2012,
                "org_name": "4-H Davis Co",
                "address": "28 E State St",
                "city": "Farmington",
                "state": "UT",
                "zip": 84025,
                "irc_section": "Utah State Universit",
                "grant_purpose": "Youth Equipment",
                "cash_grant": null,
                "non_cash_grant": 10910,
                "total_grant": 10910,
                "county": "Davis",
                "fips": 49011,
                "urban_classification": "Medium",
                "school": "FALSE",
                "Latitude": 40.98001,
                "Longitude": -111.886934,
                "Accuracy Score": 1,
                "Accuracy Type": "rooftop",
                "Number": 28,
                "Street": "E State St",
                "City_1": "Farmington",
                "State_1": "UT",
                "County_1": "Davis County",
                "Zip_1": 84025,
                "Country": "US",
                "Source": "Utah AGRC (and individual UT counties)"
            },
            "geometry": null
        },
        {
            "type": "Feature",
            "properties": {
                "year": 2014,
                "org_name": "Iron County 4-H Youth Shooting Sports Three-Peaks 4-H Shooting Club",
                "address": "714 South 1175 West",
                "city": "Cedar City",
                "state": "UT",
                "zip": 84720,
                "irc_section": "501c3",
                "grant_purpose": "Youth Equipment",
                "cash_grant": null,
                "non_cash_grant": 6100,
                "total_grant": 6100,
                "county": "Iron",
                "fips": 49021,
                "urban_classification": "Micropolitan",
                "school": "FALSE",
                "Latitude": 37.664718,
                "Longitude": -113.0785,
                "Accuracy Score": 1,
                "Accuracy Type": "rooftop",
                "Number": 714,
                "Street": "S 1175 W",
                "City_1": "Cedar City",
                "State_1": "UT",
                "County_1": "Iron County",
                "Zip_1": 84720,
                "Country": "US",
                "Source": "Utah AGRC (and individual UT counties)"
            },
            "geometry": null
        },
        {
            "type": "Feature",
            "properties": {
                "year": 2016,
                "org_name": "Utah State University Box Elder 4-H Shooting Sports Club",
                "address": "01 S Main",
                "city": "Brigham City",
                "state": "UT",
                "zip": null,
                "irc_section": "501c3",
                "grant_purpose": "General Shooting Program",
                "cash_grant": null,
                "non_cash_grant": 10701,
                "total_grant": 10701,
                "county": "Box Elder",
                "fips": 49003,
                "urban_classification": "Medium",
                "school": "FALSE",
                "Latitude": 41.510554,
                "Longitude": -112.015731,
                "Accuracy Score": 1,
                "Accuracy Type": "range_interpolation",
                "Number": 1,
                "Street": "S Main St",
                "City_1": "Brigham City",
                "State_1": "UT",
                "County_1": "Box Elder County",
                "Zip_1": 84302,
                "Country": "US",
                "Source": "TIGER\/Line® dataset from the US Census Bureau"
            },
            "geometry": null
        },
        {
            "type": "Feature",
            "properties": {
                "year": 2011,
                "org_name": "Iron County 4-H Youth Shooting Sports Three-Peaks 4-H Shooting Club",
                "address": "714 South 1175 W",
                "city": "Cedar City",
                "state": "UT",
                "zip": 84720,
                "irc_section": "501c3",
                "grant_purpose": "Youth Equipment",
                "cash_grant": 123,
                "non_cash_grant": 10911,
                "total_grant": 11034,
                "county": "Iron",
                "fips": 49021,
                "urban_classification": "Micropolitan",
                "school": "FALSE",
                "Latitude": 37.664718,
                "Longitude": -113.0785,
                "Accuracy Score": 1,
                "Accuracy Type": "rooftop",
                "Number": 714,
                "Street": "S 1175 W",
                "City_1": "Cedar City",
                "State_1": "UT",
                "County_1": "Iron County",
                "Zip_1": 84720,
                "Country": "US",
                "Source": "Utah AGRC (and individual UT counties)"
            },
            "geometry": null
        }
    ]
}